### ISSUE TITLE
Typical LQI values for good connections?

### ISSUE THREAD

**Issue by 8none1** [JNSwanson/ESP-Home-iBoost#2]
Hi!

Thanks for your work on this project, I'm really excited to be able to control my iBoost as I need to now.

I've successfully built and connected to the iBoost. 

With a cheapo eBay radio module and the default settings for frequency I was getting an LQI of 127.

Things were working fine, but I thought I would just try and nudge it up the frequecy spectrum slighly, and was then able to get an LQI of between 30 and 100.

This is lower, but do you know if it's low enough?

What is a typical "good" LQI I should be aiming for?

I'll be happy to update the `README` and provide a PR with the updated info for future readers.

Cheers!

**Comment by JNSwanson** [comment]
Hi,
The values I get from the buddy  1M away: LQI 0-3 signal -60, from the iBoost 1 floor down, but less than 5M : LQI 1-6 signal -60
sender 2 floors and about15M+ LQI 10-17 signal -81.  Lower LQI is better.  I am just using the supplied helical aerial.  BTW the third byte is the source: 01=sender, 21 is the buddy request and 22 is the iboost reply.  Please feel free to update the readme.  Before I changed the crystal I used sdrsharp and forced the firmware to do a periodic transmit so I could measure the actual frequency error and update the values in the code.
