### ISSUE TITLE
Installing/updating in the Home Assistant ESPHome addon?

### ISSUE THREAD

**Issue by no1knows** [JNSwanson/ESP-Home-iBoost#6]
Has anyone managed to use the Home Assistant esphome addon to install/update the firmware? I just tried, and got the usual CC1101_RFx-related errors. 

Does anyone know where you're supposed to copy the .cpp and .h files so that the esphome addon can see them when compiling? (Presumably somewhere in a docker container?). For now I've compiled the latest version back on my server (rather than RPi) manually using esphome cmdline, but would be great if we could update without doing that. Cheers!

**Comment by tobes49** [comment]
Yea I used the ESP home add on.

You need to install a file editor add on for home assistant.

Once installed you navigate to config/esphome/.esphome/build/cc1101/src 

Paste the files. CC1101_RFx.cpp and  CC1101_RFx.h into this directory.

Please see my screen shot but I have renamed my CC1101 to iboost so use CC1101
![Screenshot_20230820_133723_Home Assistant](https://github.com/JNSwanson/ESP-Home-iBoost/assets/73558713/1217a1cd-daf4-4811-a0bb-f1f3464196ba)

**Comment by no1knows** [comment]
Thank you, that did the trick! Unfortunately the new version still seems to hang before anything useful happens, but that's [another issue](https://github.com/JNSwanson/ESP-Home-iBoost/issues/7)!

**Comment by no1knows** [comment]
Thank you, that did the trick! Unfortunately the new version still seems to hang before anything useful happens, but that's [another issue](https://github.com/JNSwanson/ESP-Home-iBoost/issues/7)!

**Comment by srchild** [comment]
Have a look at [this thread](https://github.com/JNSwanson/ESP-Home-iBoost/issues/10)

You need to get inside the docker container if you are using HAOS

**Comment by jfdawson** [comment]
Many thanks - this explains many things I was struggling with in trying to understand HA. I did not realise things run in containers.
Ignorance is definitely not bliss!

**Comment by sm01-uk** [comment]
I am encountering the same difficulties as you @jfdawson - would you be able to provide a little more detail on what you did to sort your problem? I am running HAOS on Raspberry Pi 4 and am trying to use the ESPHome addon to install the iBoost software. Any help would be much appreciated!

**Comment by sm01-uk** [comment]
Hi John, thanks for the reply. I've managed to work out the concept of containers and now have files in the right place and a properly compiled installable. It doesn’t yet work with the iBoost but that is probably something to do with my soldering! Going to investigate further.

Thanks again for replying,
Steve.

**Comment by sm01-uk** [comment]
Morning John, one more question if I may. I've looked at the ESP logs and
the radio part of the construction clearly isn't working as there is
nothing radio related there. I suspect my soldering so am going to redo it
with a new set of boards.  Just a quick question though - I understand most
of the wiring, but how did you connect the D6 and D2 on the mini board to
the MISO on the CC1101? Initially I just soldered two wires to the CC1101
MISO and then the ends of those to D2 and D6 respectively. Is that the
correct way of doing it? Please forgive my ignorance - I am very much an
amateur!

Thanks for your help,
Steve.

**Comment by jfdawson** [comment]
Steve,

Essentially you are correct.

It took me a couple of attempts to get the wiring right, partly due to misreading the IO pins on the ESP board I had.

If you can send me a photo that shows the wiring and let me know which board model you are using  I may be able to spot something.

Possibly best to send direct to my e-mail: jfd141@gmx.co.uk as this is a bit off thread.
